name: CD (Auto Deploy)

# Qashan iske túsedi?
# Tek 'main' tarmaǵına kod 'push' qılınǵanda.
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        # SSH arqalı serverge jalǵanatuǵın tayar qural
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          # Serverde orınlanatuǵın buyrıqlar:
          script: |
            cd /home/blog-api-project

            echo "Kodtı jańalaw..."
            git pull origin main

            echo "Dockerdi qayta iske túsiriw..."
            docker compose up -d --build

            docker system prune -f